sonar.projectKey=dennis-2003_academicscopefrontend
sonar.organization=dennis-2003
sonar.projectName=AcademicScope Frontend
sonar.language=ts
sonar.sourceEncoding=UTF-8
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/*.test.*,**/vite-env.d.ts

sonar.host.url=https://sonarcloud.io
